---
- name: Load Hive Server Interactive Config
  tags: configgroup
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/config_groups"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: "{{ lookup('template','templates/hive_config_group.json.j2')}}"
    body_format: json
    validate_certs: no
    status_code: 200,201,202,409
    return_content: yes
  register: add_hive_config
  no_log: False
  ignore_errors: True

- name: Add Hive Interactive Component To Service
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/services/HIVE/components/HIVE_SERVER_INTERACTIVE"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body_format: json
    validate_certs: no
    status_code: 200,201,202,409
    return_content: yes
  register: component_install
  no_log: False
  failed_when: component_install.status not in [200, 201, 202,409]
#
# - name: Add SLIDER Interactive Component To Host
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts/{{item.host}}/host_components/SLIDER"
#     method: POST
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     # body_format: json
#     validate_certs: no
#     status_code: 200,201,202, 409
#     return_content: yes
#   register: component_add
#   no_log: False
#   with_items:
#     - "{{ llap_configs }}"
#   failed_when: component_add.status not in [200, 201, 202, 409]
#
# - name: Install SLIDER Interactive Component To Host
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts/{{item.host}}/host_components/SLIDER"
#     method: PUT
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     body_format: json
#     body:  '{"RequestInfo": {"context" :"Installing Services API"}, "HostRoles": {"state": "INSTALLED"}}'
#     validate_certs: no
#     status_code: 200,201,202
#     return_content: yes
#   register: component_install
#   no_log: False
#   with_items:
#     - "{{ llap_configs }}"
#   failed_when: component_install.status not in [200, 201, 202]

# - name: Add Hive Interactive Component To Host
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts/{{item.host}}/host_components/HIVE_SERVER_INTERACTIVE"
#     method: POST
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     body_format: json
#     validate_certs: no
#     status_code: 200,201,202, 409
#     return_content: yes
#   register: component_add
#   no_log: False
#   with_items:
#     - "{{ llap_configs }}"
#   failed_when: component_add.status not in [200, 201, 202, 409]
#
# - name: Install Hive Interactive Component To Host
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts/{{item.host}}/host_components/HIVE_SERVER_INTERACTIVE"
#     method: PUT
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     body_format: json
#     body:  '{"RequestInfo": {"context" :"Installing Services API"}, "HostRoles": {"state": "INSTALLED"}}'
#     validate_certs: no
#     status_code: 200,201,202
#     return_content: yes
#   register: component_install
#   no_log: False
#   with_items:
#     - "{{ llap_configs }}"
#   failed_when: component_install.status not in [200, 201, 202]

# - name: Wait for Hive Interactive to be installed
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/requests/{{ component_install.json.Requests.id }}"
#     method: GET
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     body_format: json
#     status_code: 200,201,202
#     validate_certs: no
#     return_content: yes
#   register: wait_component_is_installed
#   until: (wait_component_is_installed.json.Requests.request_status == 'COMPLETED' and (wait_component_is_installed.json.Requests.completed_task_count|int > 0) or
#           wait_component_is_installed.json.Requests.request_status == 'FAILED' or
#           wait_component_is_installed.json.Requests.request_status == 'TIMEDOUT' or
#           wait_component_is_installed.json.Requests.request_status == 'ABORTED')
#   retries: "{{ wait_timeout // 10 }}"
#   delay: 10
#   when: wait and component_install.json is defined

# - name: Install Hive Interactive Component
#   uri:
#     url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/request_schedules"
#     method: POST
#     force_basic_auth: yes
#     user: "{{ ambari_username }}"
#     password: "{{ ambari_password }}"
#     headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
#     body: '[{"RequestSchedule":{"batch":[{"requests":[{"type":"POST","uri":"/clusters/{{ cluster_name }}/services/HIVE/components/HIVE_SERVER_INTERACTIVE","order_id":1},{"type":"POST","uri":"/clusters/{{ cluster_name }}/hosts","RequestBodyInfo":{"RequestInfo":{"query":"Hosts/host_name.in({{ item.host }})"},"Body":{"host_components":[{"HostRoles":{"component_name":"HIVE_SERVER_INTERACTIVE"}},{"HostRoles":{"component_name":"HDFS_CLIENT"}},{"HostRoles":{"component_name":"MAPREDUCE2_CLIENT"}},{"HostRoles":{"component_name":"PIG"}},{"HostRoles":{"component_name":"SLIDER"}},{"HostRoles":{"component_name":"TEZ_CLIENT"}},{"HostRoles":{"component_name":"YARN_CLIENT"}}]}},"order_id":2},{"type":"PUT","uri":"/clusters/{{ cluster_name }}/hosts/{{ item.host }}/host_components","RequestBodyInfo":{"RequestInfo":{"context":"Install Components","operation_level":{"level":"HOST","cluster_name":"{{ cluster_name }}","host_names":"{{ item.host }}"},"query":"HostRoles/component_name.in(HIVE_SERVER_INTERACTIVE,HDFS_CLIENT,MAPREDUCE2_CLIENT,PIG,SLIDER,TEZ_CLIENT,YARN_CLIENT)"},"Body":{"HostRoles":{"state":"INSTALLED"}}},"order_id":3},{"type":"PUT","uri":"/clusters/{{ cluster_name }}/hosts/{{ item.host }}/host_components","RequestBodyInfo":{"RequestInfo":{"context":"Start HiveServer2 Interactive","operation_level":{"level":"HOST","cluster_name":"{{ cluster_name }}","host_names":"{{ item.host }}"},"query":"HostRoles/component_name.in(HIVE_SERVER_INTERACTIVE)"},"Body":{"HostRoles":{"state":"STARTED"}}},"order_id":4}]},{"batch_settings":{"batch_separation_in_seconds":1,"task_failure_tolerance":0}}]}}]'
#     body_format: json
#     validate_certs: no
#     status_code: 200,201,202
#     return_content: yes
#   register: schedule_component_install
#   no_log: False
#   with_items:
#     - "{{ llap_configs }}"
#   failed_when: schedule_component_install.status not in [200, 201, 202]


- name: Install Hive Interactive Component
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/request_schedules"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '[{"RequestSchedule":{"batch":[{"requests":[{"type":"POST","uri":"/clusters/{{cluster_name}}/services/HIVE/components/HIVE_SERVER_INTERACTIVE","order_id":1},{"type":"POST","uri":"/clusters/{{cluster_name}}/hosts","RequestBodyInfo":{"RequestInfo":{"query":"Hosts/host_name.in({{item.host}})"},"Body":{"host_components":[{"HostRoles":{"component_name":"HIVE_SERVER_INTERACTIVE"}},{"HostRoles":{"component_name":"HDFS_CLIENT"}},{"HostRoles":{"component_name":"SLIDER"}},{"HostRoles":{"component_name":"MAPREDUCE2_CLIENT"}},{"HostRoles":{"component_name":"PIG"}},{"HostRoles":{"component_name":"SLIDER"}},{"HostRoles":{"component_name":"TEZ_CLIENT"}},{"HostRoles":{"component_name":"YARN_CLIENT"}}]}},"order_id":2},{"type":"PUT","uri":"/clusters/{{cluster_name}}/hosts/{{item.host}}/host_components","RequestBodyInfo":{"RequestInfo":{"context":"Install Components","operation_level":{"level":"HOST","cluster_name":"{{cluster_name}}","host_names":"{{item.host}}"},"query":"HostRoles/component_name.in(HIVE_SERVER_INTERACTIVE,HDFS_CLIENT,MAPREDUCE2_CLIENT,PIG,SLIDER,TEZ_CLIENT,YARN_CLIENT)"},"Body":{"HostRoles":{"state":"INSTALLED"}}},"order_id":3}]},{"batch_settings":{"batch_separation_in_seconds":1,"task_failure_tolerance":0}}]}}]'
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: schedule_component_install
  no_log: False
  failed_when: schedule_component_install.status not in [200, 201, 202]

- name: Wait for Hive Interactive to be installed
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/request_schedules/{{ schedule_component_install.json.resources[0].RequestSchedule.id }}"
    method: GET
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body_format: json
    status_code: 200,201,202
    validate_certs: no
    return_content: yes
  register: wait_component_install
  until: (wait_component_install.json.RequestSchedule.status == 'COMPLETED' or
          wait_component_install.json.RequestSchedule.status == 'FAILED' or
          wait_component_install.json.RequestSchedule.status == 'TIMEDOUT' or
          wait_component_install.json.RequestSchedule.status == 'ABORTED')
  retries: "{{ wait_timeout // 10 }}"
  delay: 10
  no_log: False
  when: wait and schedule_component_install.json is defined
